name: run-unit-tests

on: push

jobs: 

  build:
  
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.10", "3.11", "3.12.0-alpha.4"]
    runs-on: ${{ matrix.os}}
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
      
    - name: Set up python 3.1
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
        
    - name: install python requirements
      run: |
        python3 -m pip install --upgrade pip
        pip3 install -r requirements.txt
        pip3 install pylint
        
    - name: Test with pytest
      run: |
        python3 -m pytest -v tests/test_factorial.py
        
    - name: Run Pylint
      run: |
        pylint --reports y --fail-under 7 mymath
    
